<?php
$included=true;
include '../../inc/db-conf.php';
include '../../inc/wallet_driver.php';
$wallet=new jsonRPCClient($driver_login);

$interval = 10;
$settings = mysqli_fetch_array(mysqli_query($link, "SELECT * FROM `system` WHERE `id`=1 LIMIT 1"));

if (mysqli_num_rows(mysqli_query($link, "SELECT * FROM `system` WHERE `id`=1 AND `deposits_last_round`<NOW()-INTERVAL $interval SECOND LIMIT 1"))==1) {
  $deposits = mysqli_query($link, "SELECT * FROM `deposits`");
  while ($dp = mysqli_fetch_array($deposits)) {
    $txs = $wallet->listtransactions('', 2000);
    foreach ($txs as $tx) {
      if ($tx['category'] == 'receive' && $tx['amount'] >= 0.00000001 && $tx['address'] == $dp['address']) { //Finds transcation to address generated by player
        if ($dp['received'] == 0) mysqli_query($link, "UPDATE `deposits` SET `received`=1,`amount`=" . $tx['amount'] . ",`txid`='" . $tx['txid'] . "'WHERE `id`=$dp[id] LIMIT 1"); //Updates information abou deposit from transcation, make it pending
        if ($tx['confirmations'] >= 1) { //Check if it's confirmed
          if (mysqli_query($link, "DELETE FROM `deposits` WHERE `id`=". $dp['id']. " LIMIT 1")) { //Deletes from deposits
            mysqli_query($link, "UPDATE `players` SET `balance`=TRUNCATE(ROUND((`balance`+" . $tx['amount'] . "),9),8) WHERE `id`=". $dp['player_id']. " LIMIT 1"); //Updates player's balance
          }
        }
      }
    }
  }
  echo json_encode(array('message' => 'Deposits were updated')); //Status message
  mysqli_query($link, "UPDATE `system` SET `deposits_last_round` = NOW() WHERE `system`.`id` = 1"); //Set last update time
}
mysqli_query($link, "DELETE FROM `deposits` WHERE `time_generated`<NOW()-INTERVAL 1 DAY");  //Deletes old transactions